# ==============================
#         COMPILE STEPS
# ==============================

# Compile the visuzlizer
[[test.compile_steps]]
program = "cargo"
args = ["build", "--release", "--bin", "vis"]
current_dir = "./tools"

# Move the compiled tester to the current directory (override the old binary)
[[test.compile_steps]]
program = "powershell.exe"
args = ["-Command", "Move-Item ./tools/target/release/vis.exe ./vis.exe -Force"]

# ==============================
#           TEST STEPS
# ==============================

# Run the user's program
[[test.test_steps]]
program = "py"
args = ["./main.py"]
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

# Run the visualizer to calculate the score
[[test.test_steps]]
program = "./vis.exe"
args = ["./tools/in/{SEED04}.txt", "./tools/out/{SEED04}.txt"]
measure_time = false
