[general]
version = "{VERSION}"

[problem]
problem_name = "{PROBLEM_NAME}"
objective = "{OBJECTIVE}"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"
